# Generated by Django 5.2 on 2025-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_call_consult_user_delete_youtubevide'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default='user'),
        ),
    ]
