# Generated by Django 5.2 on 2025-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_useraddition_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddition',
            name='role',
            field=models.TextField(),
        ),
    ]
