# Generated by Django 5.2 on 2025-05-28 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_alter_useraddition_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='email',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='name',
            new_name='client_phone',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='phone',
            new_name='master_id',
        ),
        migrations.AddField(
            model_name='call',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 5, 28)),
        ),
        migrations.AddField(
            model_name='call',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='master_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='send_status',
            field=models.BooleanField(default=False),
        ),
    ]
