# Generated by Django 5.2 on 2025-05-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_rename_email_call_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='client_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='call',
            name='master_id',
            field=models.IntegerField(),
        ),
    ]
