# Generated by Django 5.2 on 2025-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_alter_call_client_id_alter_call_master_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
