# Generated by Django 5.2 on 2025-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0014_consult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddition',
            name='role',
            field=models.TextField(choices=[('user', 'Обычный пользователь'), ('manager', 'Менеджер'), ('admin', 'Администратор')]),
        ),
    ]
