# Generated by Django 5.2 on 2025-05-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0015_alter_useraddition_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddition',
            name='role',
            field=models.TextField(),
        ),
    ]
