# Generated by Django 5.2 on 2025-05-28 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0016_alter_useraddition_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 5, 29)),
        ),
        migrations.AlterField(
            model_name='call',
            name='master_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
