# Generated by Django 5.2 on 2025-05-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0017_alter_call_created_date_alter_call_master_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='client_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='client_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='client_phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
