# Generated by Django 5.2 on 2025-05-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_call_client_email_call_client_name_call_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddition',
            name='get_call',
            field=models.BooleanField(default=False),
        ),
    ]
