# Generated by Django 5.2 on 2025-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0019_useraddition_get_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
