# Generated by Django 5.2 on 2025-05-30 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0020_questionnaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='timeout',
        ),
        migrations.AlterField(
            model_name='call',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 5, 30)),
        ),
    ]
