# Generated by Django 5.2 on 2025-05-31 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0021_remove_call_timeout_alter_call_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='user_id',
            new_name='client_id',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='useraddition',
            name='master_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 5, 31)),
        ),
    ]
