# Generated by Django 5.2 on 2025-06-01 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0022_rename_user_id_questionnaire_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddition',
            name='get_call',
        ),
        migrations.AlterField(
            model_name='call',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 6, 1)),
        ),
    ]
