# Generated by Django 5.2 on 2025-06-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0023_remove_useraddition_get_call_alter_call_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='send_status',
        ),
    ]
