# Generated by Django 5.2 on 2025-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0024_remove_call_send_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
