# Generated by Django 5.2 on 2025-06-02 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0025_alter_call_note_alter_call_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='master_phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='created_date',
            field=models.DateField(default=datetime.date(2025, 6, 2)),
        ),
    ]
